apiVersion: v1
kind: Pod
metadata:
  name: maskrcnn
  namespace: nvidia
spec:
  restartPolicy: OnFailure
  containers:
    - name: maskrcnn
      image: "quay.io/dfeddema/ngc_maskrcnn_dgxsc16"
      runAsUser: 1000
      command: ["/bin/bash", "-ec", "cd /workspace/object_detection; export INSLURM=0; export NEXP=1;  export DATADIR=/var/home/core/data/u1/mlperf/dataset/single_stage_detector; export LOGDIR=/home/mlperf/logs; printenv;  ./run_and_time.sh ; tail -f /dev/null " ]
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: NVIDIA_REQUIRE_CUDA
          value: "cuda>=5.0"
      securityContext:
        privileged: true
      resources:
        limits:
          nvidia.com/gpu: 4 # requesting 4 GPU
      volumeMounts:
      - mountPath: /home
        name: test-volume
      - mountPath: /data
        name: test-volume2
      - mountPath: /dev/shm
        name: dshm
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /var/home/core/data
  - name: test-volume2
    hostPath:
      # directory location on host
      path: /var/home/core/data/u1/mlperf/dataset/single_stage_detector
  - name: dshm
    emptyDir:
      medium: Memory
